language: python
python: 3.8
env:
  - TOXENV=django22
  - TOXENV=django30
  - TOXENV=quality
services:
  - docker
sudo: required

branches:
  only:
    - master

before_install:
  - docker-compose -f .travis/docker-compose-travis.yml up -d
  - docker exec xqueue bash -c "cd /edx/app/xqueue/xqueue/; pip3 install -r requirements/travis.txt"

script:
  - docker exec xqueue bash -c "cd /edx/app/xqueue/xqueue/ && tox -e ${TOXENV}"

after_success:
  - test $TOXENV="django22" &&
    docker exec xqueue bash -c "cd /edx/app/xqueue/xqueue/; coverage xml"
    && codecov
